linters:
  enable-all: true
  disable:
    - wsl
    - gomnd

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - goconst
        - funlen
        - scopelint
        - gocognit
    - path: doc\.go
      linters:
        - lll